

services:
  paper-db:
    image: postgres:latest
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: admin-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerceDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
